//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: partial methods (On*Changing/On*Changed) enabled
    
// Generated from: riemann.proto
namespace Riemann.Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"State")]
  public partial class ServiceState : global::ProtoBuf.IExtensible
  {
    public ServiceState() {}
    

    private long _time = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long Time
    {
      get { return _time; }
      set { OnTimeChanging(value); _time = value; OnTimeChanged();}
    }
    partial void OnTimeChanging(long value);
    partial void OnTimeChanged();

    private string _state = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string State
    {
      get { return _state; }
      set { OnStateChanging(value); _state = value; OnStateChanged();}
    }
    partial void OnStateChanging(string value);
    partial void OnStateChanged();

    private string _service = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Service
    {
      get { return _service; }
      set { OnServiceChanging(value); _service = value; OnServiceChanged();}
    }
    partial void OnServiceChanging(string value);
    partial void OnServiceChanged();

    private string _host = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"host", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Host
    {
      get { return _host; }
      set { OnHostChanging(value); _host = value; OnHostChanged();}
    }
    partial void OnHostChanging(string value);
    partial void OnHostChanged();

    private string _description = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Description
    {
      get { return _description; }
      set { OnDescriptionChanging(value); _description = value; OnDescriptionChanged();}
    }
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();

    private bool _once = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"once", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Once
    {
      get { return _once; }
      set { OnOnceChanging(value); _once = value; OnOnceChanged();}
    }
    partial void OnOnceChanging(bool value);
    partial void OnOnceChanged();
    private readonly global::System.Collections.Generic.List<string> _tags = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(7, Name=@"tags", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Tags
    {
      get { return _tags; }
    }
  

    private float _ttl = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ttl", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float Ttl
    {
      get { return _ttl; }
      set { OnTtlChanging(value); _ttl = value; OnTtlChanged();}
    }
    partial void OnTtlChanging(float value);
    partial void OnTtlChanged();
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Event")]
  public partial class Event : global::ProtoBuf.IExtensible
  {
    public Event() {}
    

    private long _time = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long Time
    {
      get { return _time; }
      set { OnTimeChanging(value); _time = value; OnTimeChanged();}
    }
    partial void OnTimeChanging(long value);
    partial void OnTimeChanged();

    private string _state = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string State
    {
      get { return _state; }
      set { OnStateChanging(value); _state = value; OnStateChanged();}
    }
    partial void OnStateChanging(string value);
    partial void OnStateChanged();

    private string _service = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Service
    {
      get { return _service; }
      set { OnServiceChanging(value); _service = value; OnServiceChanged();}
    }
    partial void OnServiceChanging(string value);
    partial void OnServiceChanged();

    private string _host = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"host", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Host
    {
      get { return _host; }
      set { OnHostChanging(value); _host = value; OnHostChanged();}
    }
    partial void OnHostChanging(string value);
    partial void OnHostChanged();

    private string _description = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Description
    {
      get { return _description; }
      set { OnDescriptionChanging(value); _description = value; OnDescriptionChanged();}
    }
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    private readonly global::System.Collections.Generic.List<string> _tags = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(7, Name=@"tags", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Tags
    {
      get { return _tags; }
    }
  

    private float _ttl = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ttl", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float Ttl
    {
      get { return _ttl; }
      set { OnTtlChanging(value); _ttl = value; OnTtlChanged();}
    }
    partial void OnTtlChanging(float value);
    partial void OnTtlChanged();
    private readonly global::System.Collections.Generic.List<Attribute> _attributes = new global::System.Collections.Generic.List<Attribute>();
    [global::ProtoBuf.ProtoMember(9, Name=@"attributes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Attribute> Attributes
    {
      get { return _attributes; }
    }
  

    private long _metricSint64 = default(long);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"metric_sint64", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long MetricSint64
    {
      get { return _metricSint64; }
      set { OnMetricSint64Changing(value); _metricSint64 = value; OnMetricSint64Changed();}
    }
    partial void OnMetricSint64Changing(long value);
    partial void OnMetricSint64Changed();

    private double _metricD = default(double);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"metric_d", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double MetricD
    {
      get { return _metricD; }
      set { OnMetricDChanging(value); _metricD = value; OnMetricDChanged();}
    }
    partial void OnMetricDChanging(double value);
    partial void OnMetricDChanged();

    private float _metricF = default(float);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"metric_f", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float MetricF
    {
      get { return _metricF; }
      set { OnMetricFChanging(value); _metricF = value; OnMetricFChanged();}
    }
    partial void OnMetricFChanging(float value);
    partial void OnMetricFChanged();
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Query")]
  public partial class Query : global::ProtoBuf.IExtensible
  {
    public Query() {}
    

    private string _string = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"string", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string String
    {
      get { return _string; }
      set { OnStringChanging(value); _string = value; OnStringChanged();}
    }
    partial void OnStringChanging(string value);
    partial void OnStringChanged();
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg")]
  public partial class Msg : global::ProtoBuf.IExtensible
  {
    public Msg() {}
    

    private bool _ok = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ok", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Ok
    {
      get { return _ok; }
      set { OnOkChanging(value); _ok = value; OnOkChanged();}
    }
    partial void OnOkChanging(bool value);
    partial void OnOkChanged();

    private string _error = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Error
    {
      get { return _error; }
      set { OnErrorChanging(value); _error = value; OnErrorChanged();}
    }
    partial void OnErrorChanging(string value);
    partial void OnErrorChanged();
    private readonly global::System.Collections.Generic.List<ServiceState> _states = new global::System.Collections.Generic.List<ServiceState>();
    [global::ProtoBuf.ProtoMember(4, Name=@"states", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ServiceState> States
    {
      get { return _states; }
    }
  

    private Query _query = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"query", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Query Query
    {
      get { return _query; }
      set { OnQueryChanging(value); _query = value; OnQueryChanged();}
    }
    partial void OnQueryChanging(Query value);
    partial void OnQueryChanged();
    private readonly global::System.Collections.Generic.List<Event> _events = new global::System.Collections.Generic.List<Event>();
    [global::ProtoBuf.ProtoMember(6, Name=@"events", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Event> Events
    {
      get { return _events; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Attribute")]
  public partial class Attribute : global::ProtoBuf.IExtensible
  {
    public Attribute() {}
    
    private string _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Key
    {
      get { return _key; }
      set { OnKeyChanging(value); _key = value; OnKeyChanged();}
    }
    partial void OnKeyChanging(string value);
    partial void OnKeyChanged();

    private string _value = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Value
    {
      get { return _value; }
      set { OnValueChanging(value); _value = value; OnValueChanged();}
    }
    partial void OnValueChanging(string value);
    partial void OnValueChanged();
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}